### ISSUE TITLE
New verification code on each save

### ISSUE THREAD

**Issue by amcgavin** [JakeBar/weather-warner#29]
should this be wrapped in:
```
super().save(*args, **kwargs)
if not self.verification_code and self.pk:
    ...
```

https://github.com/JakeBar/weather-warner/blob/082c24c46af98fdd0b3baf453c29e8a17446f552/backend/weatherwarner/models.py#L37

**Comment by JakeBar** [comment]
https://github.com/JakeBar/weather-warner/pull/32

**Comment by JakeBar** [comment]
https://github.com/JakeBar/weather-warner/pull/33
